### ISSUE TITLE
Integrate Scheduling workflows in Task List

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#810]
As a developer, I'd like to integrate the following scheduling workflows into Task list page. 

 - [x] Global actions
 - [x] Group actions
 - [x] Table in-line actions
 - [x] Execution status per row-item
 - [x] Consistent UI/UX with rest of the list pages
 - [ ] Test coverage

child of #809
